[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
restartPolicy = "always"
maxRetries = 5

[deploy.env]
NODE_ENV = "production"
RAILWAY_ENVIRONMENT = "production"